SkiAssistWebsite/Models/AddStudent.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SkiAssistWebsite.Models
{
    public class AddStudent
    {
        public int? StudentId { get; set; }

        [Required]
        [Display(Name = "First Name")]
        [StringLength(50)] 
        public string StudentFirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string StudentLastName { get; set; }

        [Required]
        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]
        public DateTime StudentDob { get; set; }

        [Required]
        [Display(Name = "Ticket Number")]
        [StringLength(50)]
        public string TicketNumber { get; set; }

        [Required]
        [Display(Name = "Diet Requerment")]
        [StringLength(50)]
        public string DietRequerment { get; set; }

        [Required]
        [Display(Name = "Medical Requerment")]
        [StringLength(100)]
        public string MedicalRequerment { get; set; }
    }
}

SkiAssistWebsite/Models/Student.cs
namespace SkiAssistWebsite.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string TicketNumber { get; set; }
        public string CurrentClass { get; set; }
        public string Teacher { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public int StudentAge { get; set; }
        public string SearchString { get; set; }

        public Student(int studentId, string ticketNum, string currentCurrentClass, string teacher, string studentFirstName, string studentLastName, int studentAge)
        {
            StudentId = studentId;
            TicketNumber = ticketNum; 
            CurrentClass = currentCurrentClass;
            Teacher = teacher;
            StudentFirstName = studentFirstName;
            StudentLastName = studentLastName;
            StudentAge = studentAge;
        }
    }
}

SkiAssistWebsite/ViewModels/AddStudentViewModel.cs
namespace SkiAssistWebsite.ViewModels
{
    public class AddStudentViewModel
    {
        
    }
}

SkiAssistWebsite/ViewModels/StudentListViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SkiAssistWebsite.Helper;
using SkiAssistWebsite.Models;

namespace SkiAssistWebsite.ViewModels
{
    public class StudentListViewModel
    {
        public List<Student> Students { get; set; }
        [Display(Name = "Search by Id, Name or TicketNumber")]
        public string SearchString { get; set; }

        public StudentListViewModel()
        {
            var studentTaskList = HttpHelper.GetList<Student>("api/students");
            var students = new List<Student>();
            foreach (var student in studentTaskList.Result)
            {
                students.Add(student);
            }

            Students = students;
        }
    }
}

SkiAssistWebsite/Controllers/AddStudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SkiAssistWebsite.Controllers
{
    public class AddStudentsController : Controller
    {
        // GET: AddStudents
        public ActionResult Index()
        {
            return View();
        }
    }
}

SkiAssistWebsite/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using SkiAssistWebsite.Helper;
using SkiAssistWebsite.Models;
using SkiAssistWebsite.ViewModels;

namespace SkiAssistWebsite.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile/StudentProfile/{id}
        public ActionResult StudentProfile(int id)
        {
            var student = HttpHelper.Get<Student>("api/students", id).Result;
            var guardians = HttpHelper.GetList<Guardian>("/api/studentguardian/guardiansviastudentid/", id);
            var profileVm = new ProfileViewModel();
            var guardianList = new List<Guardian>();

            foreach (var guardian in guardians.Result)
            {
                if (!String.IsNullOrWhiteSpace(guardian.GuardianFirstName) && !String.IsNullOrWhiteSpace(guardian.GuardianLastName))
                {
                    guardianList.Add(guardian);
                }
            }

            profileVm.Student = student;
            profileVm.Guardian = guardianList;

            return View(profileVm);
        }

//        public async Task<Student> GetStudent(int studentId)
//        {
//
//            var uriBaseAddress = HttpHelper.UriBaseAddress();
//            var client = new HttpClient { BaseAddress = uriBaseAddress };
//
//
//            var responseAsync = client.GetAsync("/api/students/" + studentId).Result;
//            var jsonAsString = await responseAsync.Content.ReadAsStringAsync();
//
//            var deserializedStudentObject = JsonConvert.DeserializeObject<Student>(jsonAsString);
//
//
//            return deserializedStudentObject;
//
//        }
//
//        public async Task<List<Guardian>> GetGuardian(int studentId)
//        {
//
//            var uriBaseAddress = HttpHelper.UriBaseAddress();
//            var client = new HttpClient { BaseAddress = uriBaseAddress };
//
//            var responseAsync = client.GetAsync("/api/studentguardian/guardiansviastudentid/" + studentId).Result;
//            var jsonAsString = await responseAsync.Content.ReadAsStringAsync();
//
//            var deserializedGuardianObject = JsonConvert.DeserializeObject<List<Guardian>>(jsonAsString);
//
//            return deserializedGuardianObject;
//
//        }
    }
}

SkiAssistWebsite/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.Owin.Security.Provider;
using Newtonsoft.Json;
using SkiAssistWebsite.Helper;
using SkiAssistWebsite.Models;
using SkiAssistWebsite.ViewModels;

namespace SkiAssistWebsite.Controllers
{
    public class StudentController : Controller
    {

        #region Create new student and post to database

        public ActionResult AddStudent()
        {
            AddDiet addDiet = new AddDiet();
            addDiet.AddStudent = new AddStudent();

            List<DietList> dietList = new List<DietList>();
            dietList.Add(new DietList() { ID = 1, DietRequirement = "Halal" });
            dietList.Add(new DietList() { ID = 2, DietRequirement = "vagiterian2" });
            dietList.Add(new DietList() { ID = 3, DietRequirement = "vagiterian3" });
            dietList.Add(new DietList() { ID = 3, DietRequirement = "vagiterian3" });
            addDiet.DietList = dietList; 

            return View(addDiet);
        }
        
        public ActionResult PostStudent(AddStudent addStudent)
        {
            if (!ModelState.IsValid)
            {
                var addStudentVm = addStudent;
                return View("AddStudent", addStudentVm);
            }

            var newStudent = new AddStudent()
            {
                StudentDob = addStudent.StudentDob,
                StudentFirstName = addStudent.StudentFirstName,
                StudentLastName = addStudent.StudentLastName,
                TicketNumber = addStudent.TicketNumber
            };

            var studentAsJson = JsonConvert.SerializeObject(newStudent);
            var response = HttpHelper.Post(studentAsJson, "api/poststudent");
            var newStudentId = response.Result.Content.ReadAsStringAsync().Result;
            return RedirectToAction("AddGuardian", "Guardian", new { id = newStudentId });
        }

        #endregion

        #region Get students from the database

        // GET: Student
        [Route("student/studentList")]
        [HttpGet]
        public ActionResult StudentList()
        {
            var studentListVm = new StudentListViewModel();

            return View(studentListVm);
        }

        [Route("student/studentSearch")]
        public ActionResult StudentSearch(StudentListViewModel studentListVm)
        {
            var lowerString = studentListVm.SearchString?.ToLower(); // check if searchString is null. if not then save it in lowerString

            if (!string.IsNullOrWhiteSpace(studentListVm.SearchString))
            {
                // will check searchString against first name, last name, studentId and ticket number and return any records that match

                studentListVm.Students = studentListVm.Students
                    .Where(s => s.StudentFirstName.ToLower().Contains(lowerString) || 
                                s.StudentLastName.ToLower().Contains(lowerString) ||
                                s.TicketNumber.ToLower().Contains(lowerString) ||
                                s.StudentId.ToString().ToLower().Contains(lowerString)) 
                    .ToList();
            }

            return View("StudentList", studentListVm);
        }

        #endregion
    } 
}

SkiAssistWebsite/Views/Student/AddStudent.cshtml
@using System.Activities.Expressions
@using System.Web.Management
@using SkiAssistWebsite.Controllers
@model SkiAssistWebsite.Models.AddDiet

@{
    ViewBag.Title = "New Student";
    Layout = "/views/shared/_NewLayout.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <!-- Gaurdian Details-->
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="header">
                        <div id="new">
                            <h4 class="title">Student Details</h4>
                        </div>
                        <div class="content">

                            @using (Html.BeginForm("PostStudent", "Student")) 
                            {
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.StudentFirstName)
                                            @Html.TextBoxFor(m => m.AddStudent.StudentFirstName, new { @class = "form-control", placeholder = "First Name" })
                                            @Html.ValidationMessageFor(m => m.AddStudent.StudentFirstName)
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.StudentLastName)
                                            @Html.TextBoxFor(m => m.AddStudent.StudentLastName, new { @class = "form-control", placeholder = "Last Name" })
                                            @Html.ValidationMessageFor(m => m.AddStudent.StudentLastName)
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.TicketNumber)
                                            @Html.TextBoxFor(m => m.AddStudent.TicketNumber, new { @class = "form-control", placeholder = "Ticket Number" })
                                            @Html.ValidationMessageFor(m => m.AddStudent.TicketNumber)
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.StudentDob)
                                            @Html.EditorFor(m => m.AddStudent.StudentDob, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(m => m.AddStudent.StudentDob)
                                        </div>
                                    </div>
                                </div>
                                <!--dietary issue section start-->
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.DietRequerment)
                                            <fieldset class="dietListBox">
                                                @foreach (var item in Model.DietList)
                                                {
                                                    <div class="col-md-4">
                                                        <input type="checkbox" name="Halal" value="Halal" />
                                                        <label for="Halal">@item.DietRequirement</label>
                                                    </div>
                                                    <br />
                                                }
                                                <div>
                                                    @Html.TextBoxFor(m => m.AddStudent.DietRequerment, new { @class = "form-control", placeholder = "Diet Requerment" })
                                                    @Html.ValidationMessageFor(m => m.AddStudent.DietRequerment)
                                                </div>

                                            </fieldset>
                                        </div>
                                        </div>
                                    </div>
                                <!--dietary issue section end-->
                                <!--medical issue section start-->
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.AddStudent.MedicalRequerment)
                                            @Html.TextAreaFor(m => m.AddStudent.MedicalRequerment, new { @class = "form-control", placeholder = "Medical Requerment" })
                                            @Html.ValidationMessageFor(m => m.AddStudent.MedicalRequerment)
                                        </div>
                                    </div>
                                </div>
                                <!--medical issue section end-->
                                <button type="submit" class="btn btn-info btn-fill pull-middle">Add New Student</button>
                            }
                            <div class="clear-fix"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SkiAssistWebsite/Views/Student/StudentList.cshtml
@using System.Web.UI.WebControls
@using SkiAssistWebsite.Models
@model SkiAssistWebsite.ViewModels.StudentListViewModel

@{
    ViewBag.Title = "Students";
    Layout = "/views/shared/_NewLayout.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Student List</h4>
                        <p class="category"><!--Subtitle can go here. Not sure what it will be yet.--></p>
                        <div class="header">
                            <h4 class="title">Student Search</h4>
                        </div>
                        <div class="content">
                            @using (Html.BeginForm("StudentSearch", "Student"))
                            {
                                <div class="row">
                                    <div class="col-md-10">
                                        <div class="search">
                                            @Html.LabelFor(m => m.SearchString)
                                            @Html.TextBoxFor(m => m.SearchString, new { @class = "form-control"})
                                        </div>
                                    </div>

                                    <div class="col-md-2">
                                        <button type="submit" class="btn btn-info btn-fill">Search</button>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-hover table-striped">
                            <thead>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Age</th>
                            <th>Ticket Number</th>
                            </thead>
                            <tbody>
                                @{
                                    if (Model.Students.Count == 0)
                                    {
                                        <h3 class="title">There are no students currently in the system</h3>
                                    }
                                    else
                                    {
                                        foreach (var student in Model.Students)
                                        {
                                            string studentName = student.StudentFirstName + " " + student.StudentLastName;
                                            <tr>
                                                <td>@student.StudentId</td>
                                                <td>@Html.ActionLink(studentName, "StudentProfile", "Profile", new { id = student.StudentId }, null)</td>
                                                <td>@student.StudentAge</td>
                                                <td>@student.TicketNumber</td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>